# Generated by Django 2.2.14 on 2020-08-19 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_auth', models.CharField(max_length=500)),
                ('post_category', models.CharField(max_length=500)),
                ('post_tag', models.CharField(max_length=500)),
                ('post_date', models.DateField()),
                ('post_image', models.FileField(upload_to='post')),
                ('post_desc', models.TextField(max_length=50000000)),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_nm',
            new_name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='author_nm',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='book_desc',
            field=models.TextField(default='none', max_length=500000),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(default='none', upload_to='book'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_tag',
            field=models.CharField(default='book-tag', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='branch',
            field=models.CharField(choices=[('NONE', 'NONE'), ('All', 'All'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EE', 'EE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_nm',
            field=models.CharField(choices=[('NONE', 'NONE'), ('Alok Publication', 'Alok Publication'), ('BK Publication', 'BK Publication'), ('EM Publication', 'EM Publication'), ('Khanna Publication', 'Khanna Publication')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 15, 34, 31, 131749, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_nm',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='orderbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(to='core.orderbook'),
        ),
    ]
