# Generated by Django 2.2.14 on 2020-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200819_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default='First Edition', max_length=100),
        ),
    ]
