# Generated by Django 2.2.14 on 2020-08-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_tag',
        ),
    ]
