# Generated by Django 2.2.14 on 2020-08-28 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
