# Generated by Django 2.2.14 on 2020-08-28 15:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200828_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
