# Generated by Django 2.2.14 on 2020-08-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200829_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
