# Generated by Django 2.2.14 on 2020-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_book_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
