# Generated by Django 2.2.14 on 2020-09-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Customer'),
        ),
    ]
