# Generated by Django 2.2.14 on 2020-11-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orderbook_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='customer',
        ),
    ]
